# Generated by Django 5.0.6 on 2026-05-01 10:27

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket', models.BigIntegerField(blank=True, help_text='MT5 deal/position ticket. Used for deduplication when importing.', null=True, unique=True)),
                ('symbol', models.CharField(db_index=True, max_length=32)),
                ('order_type', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=8)),
                ('volume', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12)),
                ('open_time', models.DateTimeField(db_index=True)),
                ('close_time', models.DateTimeField(db_index=True)),
                ('open_price', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=18)),
                ('close_price', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=18)),
                ('profit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('commission', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('swap', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('comment', models.CharField(blank=True, default='', max_length=255)),
                ('magic_number', models.BigIntegerField(blank=True, null=True)),
                ('mae', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum Adverse Excursion (in account currency).', max_digits=18, null=True)),
                ('mfe', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum Favorable Excursion (in account currency).', max_digits=18, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-close_time', '-id'],
                'indexes': [models.Index(fields=['close_time'], name='trades_trad_close_t_9382d3_idx'), models.Index(fields=['symbol', 'close_time'], name='trades_trad_symbol_d39392_idx')],
            },
        ),
    ]
