# Generated by Django 5.0.6 on 2026-05-01 15:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Owner of the trade. Null only for legacy rows imported pre-auth.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trades', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trade',
            name='ticket',
            field=models.BigIntegerField(blank=True, help_text='MT5 deal/position ticket. Used for per-user deduplication when importing.', null=True),
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['user', 'close_time'], name='trades_trad_user_id_452a48_idx'),
        ),
        migrations.AddConstraint(
            model_name='trade',
            constraint=models.UniqueConstraint(condition=models.Q(('ticket__isnull', False)), fields=('user', 'ticket'), name='trade_unique_user_ticket'),
        ),
    ]
